services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        WWWUSER: 1001
        WWWGROUP: 1001
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

volumes:
  db_data: